services:
- type: pserv
  repo: https://github.com/naksh-atra/translation_assignment_render

  # Change this to the path containing your Dockerfile
  rootDir: translation_assignment_render

  name: livekit-translator
  runtime: image

  # Free plan is not available for private services
  plan: free

  # Environment variables are stored in a group
  # created in the Render dashboard.
  envVars:
  - fromGroup: Environment Variables
  region: virginia

  # 300s is the standard allowed maximum. Talk to render.com support if you need this increased.
  maxShutdownDelaySeconds: 300

  # Sane defaults
  scaling:
    minInstances: 1
    maxInstances: 4
    targetCPUPercent: 60
    targetMemoryPercent: 60
version: "1"
